### ISSUE TITLE
Feature Request: Additive coding

### ISSUE THREAD

**Issue by FrankD** [MicrosoftGenomics/PySnpTools#1]
Hi,

Love the package, but I have a small request regarding the coding of the SNP values. It seems that currently, if we have (AA, AG, GG) you encode this as (0,1,2) if A1=A in the BIM file. Is this correct?

If so, this is the inverse of the additive encoding that PLINK uses:

> The 'AD' modifier causes an additive (0/1/2) + dominant (het = 1, otherwise 0) component file, suitable for loading from R, to be generated. 'A' is the same, except without the dominance component.
> 
> ```
> By default, A1 alleles are counted; this can be customized with --recode-allele. --recode-allele's input file should have variant IDs in the first column and allele IDs in the second.
> By default, the header line for .raw files only names the counted alleles. To include the alternate allele codes as well, add the 'include-alt' modifier.
> Haploid additive components are 0/2-valued instead of 0/1-valued, to maintain a consistent scale on the X chromosome.
> ```

I think the PLINK encoding makes more sense, so would suggest to change it so that by default A1=A in the BIM file leads to (2,1,0), perhaps with an argument in the read() method that allows you to choose the alternative encoding. Also, it would be good to discuss the encoding somewhere more prominently in the documentation; I had to go through a lot of trial and error to find out what was going on.

Anyway, thanks for making this package available, it has made processing SNPs in Python easier for me!

**Comment by CarlKCarlK** [comment]
Frank,
 
Thanks so much for your use of PySnpTools and your suggestion. Here is what I propose:
 
Adding a new option 'count_A1' to the Bed constructor (and the static write method).
 
Usage example:
 
snpdata = Bed('../examples/toydata.bed',count_A1=False)keeps the behavior as it is, for backwards compatibility
 
snpdata = Bed('../examples/toydata.bed',count_A1=True)changes to the PLINK standard.
 
If the option is not given, it will default to False (again, for backwards compatibility) but also give a warning message that 'in the future the default will be changed to True.'
 
The docs would be updated to something like this:
 
class pysnptools.snpreader.Bed(filename, count_A1=None)¶
A SnpReader for random-access reads of Bed/Bim/Fam files from disk.
See SnpReader for details and examples.
The format is described in http://pngu.mgh.harvard.edu/~purcell/plink/binary.shtml.
Constructor:Parameters:filename (string) – The *.bed file to read. The ‘.bed’ suffix is optional. The related *.bim and *.fam files will also be read.count_A1 (bool) – Tells if it should count the number of A1 alleles (the PLINK standard) or the number of A2 alleles. False is the current default, but in the future the default will change to True 
What do you think?
 
-Carl
 
 
Date: Fri, 4 Mar 2016 05:47:14 -0800

**Comment by FrankD** [comment]
Hi Carl,

Sounds great! This will definitely cover my expected use cases, but I'm curious why you'd want to set the encoding in the Bed constructor rather than in the read method (the latter would enable someone to switch encoding without creating a new Bed object).

Regards,

Frank

**Comment by CarlKCarlK** [comment]
Frank,
 
Excellent and thanks for the feedback. I hope to the new version out this week.
 
Good question about the constructor vs the read method. The reason I don't want to put the count_A1 option in the "read" method is because many other classes  -- _Subset (which does the slicing and dicing), Pheno, PstReader, KernelReader, SnpData, etc -- basically share the same "read" code. But for the other classes, the option doesn't make sense. Not only does this save code (which makes everything more testable), it also allows new reader class to wrap the functionality of all the other reader classes. For example, I'm working on a new reader that can efficiently read any number of Bed readers with different individuals as if they were one file. And it works, not just with Bed readers, but with all the other readers.
 
Thanks for using PySnpTools,
 
Yours,
Carl
 
Date: Mon, 7 Mar 2016 01:47:22 -0800

**Comment by CarlKCarlK** [comment]
Frank,
 
I'm happy to report that PySnpTools now has your requested feature. The new version is on GitHub and PyPi.
 
Thanks again for your feedback.
 
Yours,
Carl
 
From: carlk@msn.com
To: reply@reply.github.com
Subject: RE: [PySnpTools] Feature Request: Additive coding (#1)
Date: Mon, 7 Mar 2016 08:39:59 -0800




Frank,
 
Excellent and thanks for the feedback. I hope to the new version out this week.
 
Good question about the constructor vs the read method. The reason I don't want to put the count_A1 option in the "read" method is because many other classes  -- _Subset (which does the slicing and dicing), Pheno, PstReader, KernelReader, SnpData, etc -- basically share the same "read" code. But for the other classes, the option doesn't make sense. Not only does this save code (which makes everything more testable), it also allows new reader class to wrap the functionality of all the other reader classes. For example, I'm working on a new reader that can efficiently read any number of Bed readers with different individuals as if they were one file. And it works, not just with Bed readers, but with all the other readers.
 
Thanks for using PySnpTools,
 
Yours,
Carl
 
Date: Mon, 7 Mar 2016 01:47:22 -0800

**Comment by FrankD** [comment]
Great, thanks a lot Carl!

Regards,

Frank
